### ISSUE TITLE
Netlify

### ISSUE THREAD

**Issue by mdestafadilah** [bpk68/parcel-template#7]
Is it working with netlify ?

**Comment by bpk68** [comment]
Hey @mdestafadilah, apologies for the long delay in responding to you here. It looks like I'm not getting notifications about this sort of stuff. 

So, Parcel will do largely the same as Webpack and similar bundlers. If you run something like `yarn build` you'll get a nicely packaged set of files that you should be able to host anywhere. I can't guarantee that this will work on host x, y or z, but I can't see why there'd be an issue with it.
